name: AwesomeTx
description: This transaction is awesome, I have to tell everyone!
title: ""
labels: ["AwesomeTx"]
body:
  - type: input
    id: txhash
    attributes:
      label: Transaction Hash
      description: ""
      placeholder: "e.g. 0x9369a389f32dabf118a3c24f166014ed9f9f0d6682421dfb9e05034459a323ed"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Tell us why this transaction is Awesome!
      value: ""
    validations:
      required: true