name: AwesomeTx
title: "sample: JIT in Uniswap v3"
labels: ["AwesomeTx"]
body:
  - type: input
    id: txhash
    attributes:
      label: Transaction Hash
      placeholder: "e.g. 0x9369a389f32dabf118a3c24f166014ed9f9f0d6682421dfb9e05034459a323ed"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Tell us why this transaction is Awesome!
      value: "This transaction earn $100,000"
    validations:
      required: true
